spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allow-credentials: true
                allowed-origins:
                  - http://localhost:3000
                allowed-headers: "*"
                allowed-methods:
                  - PUT
                  - GET
                  - POST
                  - PATCH
                  - DELETE
                  - OPTIONS

          routes:
            - id: member-service
              uri: lb://member-service
              predicates:
                - Path=/api/members/**

            - id: transaction-service
              uri: lb://transaction-service
              predicates:
                - Path=/api/transactions/**

            - id: board-service
              uri: lb://board-service
              predicates:
                - Path=/api/boards/**

            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/notifications/**

            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/products/**

            - id: admin-service
              uri: lb://admin-service
              predicates:
                - Path=/api/administrators/**

            - id: customer-service
              uri: lb://customer-service
              predicates:
                - Path=/api/cs/**

          default-filters:
            - name: AuthenticationFilter

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: ${JWT_SECRET}
  accessTokenExpiration: 300000
  refreshTokenExpiration: 86400000
