server:
  error:
    whitelabel:
      enabled: false

spring:
  web:
    resources:
      add-mappings: false

  flyway:
    enabled: false

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test

  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create
    database: h2
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
    open-in-view: false

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor.sql: trace

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
  cache:
    type: redis

  jwt:
    secret: ${JWT_SECRET}
    access-token:
      expire: 300000
    refresh-token:
      expire: 86400000

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

  tomcat:
    max-swallow-size: 100MB

cookie:
  secure: false
  same-site: Lax

r2:
  bucketName: ${R2_BUCKET_NAME}
  endpointUrl: ${R2_ENDPOINT_URL}
  region: APAC
  accessKey: ${R2_ACCESS_KEY}
  secretKey: ${R2_SECRET_KEY}

logging:
  slack-info:
    webhook-uri: ${SLACK_WEB_HOOK_URI_INFO}
    channel: log-info
    username: HOMEPAGE INFO LOG BOT
    emoji: eyes

  slack-error:
    webhook-uri: ${SLACK_WEB_HOOK_URI_ERROR}
    channel: log-error
    username: HOMEPAGE ERROR LOG BOT
    emoji: exclamation

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true


resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 80
        slow-call-duration-threshold: 10s
        permitted-number-of-calls-in-half-open-state: 3
        max-wait-duration-in-half-open-state: 0
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 10s
    instances:
      circuit:
          base-config: default
  bulkhead:
    configs:
      default:
        max-concurrent-calls: 5
        max-wait-duration: 0
    instances:
      bulkhead:
        base-config: default